%
% reads the XLS file generated by the Agilent CSA N1996A
% 
clc
clear all
% close all


% file names
files={'C:\Users\studenti\Desktop\FOW\Multimode\2019\GX\Data_XXX.xls'};

% number of files
nf=length(files);

% reads data
for f=1:nf
    d=importdata(files{f});
    if f==1
        % initialize frequencies and data 
        freq=d.data(:,1);
        data=zeros(length(freq),nf);
    end
    % sign must be inverted
    data(:,f)=-d.data(:,3);
end

% plot data
plot(freq, data);

% figure, plot(freq, -data(:,1)+data(:,2))
